apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aspnet-core3.fullname" . }}
  labels:
    {{- include "aspnet-core3.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "aspnet-core3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aspnet-core3.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aspnet-core3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if or .Values.image.secretsEnvVarts }}
          env:
          {{- toYaml .Values.image.secretsEnvVarts | nindent 10 }}
{{- end }}
{{ if or .Values.image.volumeFileMounts }}
          volumeMounts:
{{- range .Values.image.volumeFileMounts }}
          - name: {{.volumeName}}
            mountPath: {{.mountPath}}{{.mountFile}}
            {{- if .mountFile }}
            subPath: {{.mountFile}}
            {{- end }}
{{- end }}
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
{{- with .Values.image.healty }}
{{- if .enabled }}
          livenessProbe:
            httpGet:
              path: {{ .livenessProbePath | default "/health" | quote }}
              port: http
          readinessProbe:
            httpGet:
              path: 
              port: http
{{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{ if or .Values.image.volumeFileMounts }}
      volumes:
{{- range .Values.image.volumeFileMounts }}
        - name: {{.volumeName}}
          configMap:
            name: {{.configMapName}}
            items:
              - key: {{.configMapKey}}
                path: {{.mountFile}}
{{- end }}
{{- end }}